# IS NULL - 경기도에 위치한 식품창고 목록 출력하기

## 문제

![이미지](https://velog.velcdn.com/images/tkddud95920/post/cf9fd329-dfeb-4e22-8cb2-76f93ce62e71/image.png)

## 접근

In [ ]:
# 경기도에 위치한 창고만 살펴보기 위해 WHERE, LIKE로 필터링
# 냉동시설 여부에 null값이 있는 경우 N으로 출력 → select절에서 if문 사용
# 창고 ID에 따라 asc 정렬

## 풀이

In [ ]:
"""
SELECT warehouse_id, warehouse_name, address
      , IF(freezer_yn IS NULL, 'N', freezer_yn) AS freezer_yn
FROM food_warehouse
WHERE address LIKE '%경기%'
ORDER BY warehouse_id;
"""