# IS NULL - 이름이 없는 동물의 아이디

## 문제

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FUhrlT%2FbtrwopaFKrf%2FHYTeXs8AilxIURbfwmqdO1%2Fimg.png)

## 접근

In [ ]:
# 이름이 NULL값인 데이터 WHERE로 필터링
# ID에 따라 asc 정렬

## 풀이

In [ ]:
"""
SELECT animal_id
FROM animal_ins
WHERE name IS NULL
ORDER BY animal_id;
"""